### ISSUE TITLE
1.2.0 clojars

### ISSUE THREAD

**Issue by hozumi** [cgrand/moustache#10]
Hi,
Would you upload 1.2.0 into clojars repo?

Thanks.

**Comment by cgrand** [comment]
There is more to 1.2.0 than the new syntax. I just pushed a 1.2.0-alpha1 though.

**Comment by hozumi** [comment]
Thanks!

**Comment by cgrand** [comment]
@hozumi if you use the alpha features, I'd be happy to have some feedback -- well, even if you don't use alpha features.

**Comment by hozumi** [comment]
Hi Christophe,
I don't use new features and get no problem currently.
I requested 1.2.0 because I want to avoid range dependency specified in preview version.
And to be honest, I still don't know what is new in 1.2.0.
I would like to see concreate example instead of syntax.html.
